version: '3.8'

services:
  database:
    image: postgres
    container_name: laravel-repository-db
    working_dir: /data/pgsql
    environment:
      POSTGRES_PASSWORD: pgsql_password
      POSTGRES_DB: laravel_repository
    expose:
      - 5432
    ports:
      - 5432:5432
    command: -p 5432

  backend:
    build: .
    image: laravel-repository-api
    container_name: laravel-repository-api
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - .:/var/www/laravel-repository
      - ./.apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8000:80
    stdin_open: true
    tty: true

  redis:
    image: redis:5.0
    container_name: laravel-repository-redis
    restart: unless-stopped
    ports:
      - 6379:6379